### ISSUE TITLE
CCDemo - Video continues to play on Chromecast after disconnect

### ISSUE THREAD

**Issue by jabberdabber** [kaltura/player-sdk-demo-ios#3]
Hi,

We have the CCDemo working and have been studying it as an example for our own app. Everything seems to work except that when disconnecting from Chromecast, the video continues to play on Chromecast. Is there a way to stop video playback on Chromecast when disconnecting?

**Comment by kaltura-hooks** [comment]
Hi @jabberdabber,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
- Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
  please provide as much details as possible.
- Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
  If self hosted, are you using the RPM or deb install?
- Packages installed.
  When using RPM, paste the output for:

```
    # rpm -qa \"kaltura*\"
```

```
For deb based systems:
```

```
    # dpkg -l \"kaltura-*\"
```
- If running a self hosted ENV - provide the MySQL server version used
- If running a self hosted ENV - is this a single all in 1 server or a cluster?
- If running a self hosted ENV, while making the problematic request, run:

```
    # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```

   and paste the output.
- When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by ElizaSapir** [comment]
Hey @jabberdabber,

As you can see in our [CC documentation](https://vpaas.kaltura.com/documentation/Mobile-Video-Player-SDKs/iOS-Casting-Chromecast.html) we have 2 kinds of disconnect:

```
- (void)disconnect {
// Session won't be remove
    [_castProvider disconnectFromDevice];
}

// OR

- (void)disconnect {
// Session is removed
    [_castProvider disconnectFromDeviceWithLeave];
}

```

In your case as mentioned above if you want that the session will be removed you suppose to use:

`[_castProvider disconnectFromDeviceWithLeave];`

Please make sure to close the ticket the moment you validate that it works for you!

Best,

Eliza

**Comment by jabberdabber** [comment]
Oops, I should have taken a closer look at the documentation. It works for me. Thank you.
